"""Session-aware backtesting engine with pivot indicators for futures markets."""

__version__ = "0.1.0"

from sessionpt.analytics import (
    calculate_all_robust_metrics,
    calculate_calmar_ratio,
    calculate_kelly_fraction,
    calculate_max_drawdown,
    calculate_max_drawdown_duration,
    calculate_max_drawdown_from_trades,
    calculate_sortino_ratio,
    check_strategy_robustness,
    profit_factor_threshold_check,
)
from sessionpt.backtesting.engine import (
    EntryEvent,
    precompute_backtest_arrays,
    run_event_backtest,
    summarize_trades,
)
from sessionpt.backtesting.results import BacktestRunResult, EngineTradeRecord
from sessionpt.backtesting.specs import (
    BreakevenPolicy,
    ExecutionPolicy,
    InstrumentSpec,
    TrailingStopPolicy,
)
from sessionpt.backtesting.vectorized import VectorizedBacktester
from sessionpt.constants import (
    ALL_HOURS_SESSION,
    CLOSE_COLUMN,
    DEFAULT_SESSION_CLOSE_HOUR,
    DEFAULT_TIMEZONE,
    HIGH_COLUMN,
    LOW_COLUMN,
    OHLC_COLUMNS,
    OHLCV_COLUMNS,
    OPEN_COLUMN,
    PIVOT_LEVEL_COLUMNS,
    UTC_TIMEZONE,
    VOLUME_COLUMN,
)
from sessionpt.enums import Direction, ExitReason, PivotLevel, PivotType
from sessionpt.features import (
    add_rth_anchored_vwap,
    build_atr_mask,
    build_volume_mask,
    build_vwap_long_mask,
    build_vwap_short_mask,
    build_wick_long_mask,
    build_wick_short_mask,
    combine_entry_masks,
    compute_atr,
    compute_nmin_entry_signal,
    compute_volume_ratio,
    compute_vwap,
    compute_wick_ratios,
)
from sessionpt.filters.trend import TrendFilterConfig, calculate_trend_bias, filter_by_trend
from sessionpt.levels import add_initial_balance_levels
from sessionpt.pivots import (
    ConfluenceZone,
    add_pivot_levels_to_intraday,
    apply_directional_pivot_shift,
    calculate_all_pivot_types,
    calculate_camarilla_pivots,
    calculate_classic_pivots,
    calculate_daily_ohlc,
    calculate_dm_pivots,
    calculate_fibonacci_pivots,
    calculate_pivot_confluence,
    calculate_pivot_levels,
    calculate_traditional_pivots,
    calculate_woodie_pivots,
    find_confluence_levels,
    get_confluence_at_level,
    prepare_data_with_pivots,
    prepare_shifted_pivot_data,
)
from sessionpt.sessions import (
    build_session_mask,
    ensure_utc_index,
    get_session_ids,
    get_session_labels,
)
from sessionpt.validation.walk_forward import (
    FoldResult,
    OptResult,
    WalkForwardFold,
    generate_walk_forward_folds,
)

__all__ = [
    "ALL_HOURS_SESSION",
    "CLOSE_COLUMN",
    "DEFAULT_SESSION_CLOSE_HOUR",
    "DEFAULT_TIMEZONE",
    "HIGH_COLUMN",
    "LOW_COLUMN",
    "OHLCV_COLUMNS",
    "OHLC_COLUMNS",
    "OPEN_COLUMN",
    "PIVOT_LEVEL_COLUMNS",
    "UTC_TIMEZONE",
    "VOLUME_COLUMN",
    "BacktestRunResult",
    "BreakevenPolicy",
    "ConfluenceZone",
    "Direction",
    "EngineTradeRecord",
    "EntryEvent",
    "ExecutionPolicy",
    "ExitReason",
    "FoldResult",
    "InstrumentSpec",
    "OptResult",
    "PivotLevel",
    "PivotType",
    "TrailingStopPolicy",
    "TrendFilterConfig",
    "VectorizedBacktester",
    "WalkForwardFold",
    "add_initial_balance_levels",
    "add_pivot_levels_to_intraday",
    "add_rth_anchored_vwap",
    "apply_directional_pivot_shift",
    "build_atr_mask",
    "build_session_mask",
    "build_volume_mask",
    "build_vwap_long_mask",
    "build_vwap_short_mask",
    "build_wick_long_mask",
    "build_wick_short_mask",
    "calculate_all_pivot_types",
    "calculate_all_robust_metrics",
    "calculate_calmar_ratio",
    "calculate_camarilla_pivots",
    "calculate_classic_pivots",
    "calculate_daily_ohlc",
    "calculate_dm_pivots",
    "calculate_fibonacci_pivots",
    "calculate_kelly_fraction",
    "calculate_max_drawdown",
    "calculate_max_drawdown_duration",
    "calculate_max_drawdown_from_trades",
    "calculate_pivot_confluence",
    "calculate_pivot_levels",
    "calculate_sortino_ratio",
    "calculate_traditional_pivots",
    "calculate_trend_bias",
    "calculate_woodie_pivots",
    "check_strategy_robustness",
    "combine_entry_masks",
    "compute_atr",
    "compute_nmin_entry_signal",
    "compute_volume_ratio",
    "compute_vwap",
    "compute_wick_ratios",
    "ensure_utc_index",
    "filter_by_trend",
    "find_confluence_levels",
    "generate_walk_forward_folds",
    "get_confluence_at_level",
    "get_session_ids",
    "get_session_labels",
    "precompute_backtest_arrays",
    "prepare_data_with_pivots",
    "prepare_shifted_pivot_data",
    "profit_factor_threshold_check",
    "run_event_backtest",
    "summarize_trades",
]
