"""Shared constants for sessionpt public helpers."""

DEFAULT_TIMEZONE = "America/New_York"
UTC_TIMEZONE = "UTC"
DEFAULT_SESSION_CLOSE_HOUR = 17
DEFAULT_ETH_START_LOCAL = "18:00"
DEFAULT_ETH_END_LOCAL = "17:00"

OPEN_COLUMN = "Open"
HIGH_COLUMN = "High"
LOW_COLUMN = "Low"
CLOSE_COLUMN = "Close"
VOLUME_COLUMN = "Volume"
OHLC_COLUMNS = (OPEN_COLUMN, HIGH_COLUMN, LOW_COLUMN, CLOSE_COLUMN)
OHLCV_COLUMNS = (*OHLC_COLUMNS, VOLUME_COLUMN)

PIVOT_CENTRAL_COLUMN = "P"
PIVOT_R1_COLUMN = "R1"
PIVOT_R2_COLUMN = "R2"
PIVOT_R3_COLUMN = "R3"
PIVOT_S1_COLUMN = "S1"
PIVOT_S2_COLUMN = "S2"
PIVOT_S3_COLUMN = "S3"
PIVOT_LEVEL_COLUMNS = (
    PIVOT_CENTRAL_COLUMN,
    PIVOT_R1_COLUMN,
    PIVOT_R2_COLUMN,
    PIVOT_R3_COLUMN,
    PIVOT_S1_COLUMN,
    PIVOT_S2_COLUMN,
    PIVOT_S3_COLUMN,
)

ALL_HOURS_SESSION = "all_hours"
